2025-08-07 15:38:14,050 ERROR: Exception on /explore [GET] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 167, in explore
    return render_template('index.html',title='Explore',posts=posts.items, next_url=next_url, prev_url=prev_url)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\HP3\Desktop\MicroBlog\app\templates\index.html", line 27, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2025-08-07 15:39:38,470 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-07 15:39:47,227 ERROR: Exception on /explore [GET] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 165, in explore
    prev_url=url_for('explore',posts.prev_num) \
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: url_for() takes 1 positional argument but 2 were given
2025-08-07 15:40:49,828 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-08 11:29:08,593 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:45]
2025-08-19 15:28:36,350 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:28:36,435 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:28:36,435 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:30:27,128 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:30:27,206 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:30:27,206 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:32:23,136 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:32:23,171 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:32:23,171 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:39:07,498 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:39:07,567 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-19 15:39:07,567 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-20 12:29:04,893 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
2025-08-20 12:29:56,565 ERROR: Exception on /reset_password_request [GET] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 170, in reset_password_request
    if current_user.is_aunthenticated:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'AnonymousUserMixin' object has no attribute 'is_aunthenticated'. Did you mean: 'is_authenticated'?
2025-08-20 12:30:30,724 INFO: Microblog startup [in C:\Users\HP3\Desktop\MicroBlog\app\__init__.py:47]
